### ISSUE TITLE
Not working with mac os monterey

### ISSUE THREAD

**Issue by RubenOliveira8** [Channel-Debug/msi-gf63-thin-9rcx#1]
it does not work with mac os monterey, in verbose mode it shows up it enter in a bootloop because of the bluetooth kexts

**Comment by Channel-Debug** [comment]
Contact me in telegram group https://t.me/HackintoshLife_it i'm @GabryDark0
on Telegram

Il giorno ven 2 lug 2021 alle ore 16:46 RubenOliveira8 <
***@***.***> ha scritto:
